config/routes.rb
Rails.application.routes.draw do

  resources :locations, only: [:index] do
    collection do
      get 'store_explorer'
    end
  end

  resources :fixture_types, only: [:index] do
    collection do
      get 'nested_tables'
    end
  end

  root 'locations#index'
  get 'characters/index'

end

app/models/character.rb
class Character < ActiveRecord::Base
end

app/models/fixture_type.rb
class FixtureType < ActiveRecord::Base
  has_and_belongs_to_many :locations
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_and_belongs_to_many :fixture_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end
end

app/controllers/fixture_types_controller.rb
class FixtureTypesController < ApplicationController
  def index

  end

  def nested_tables
    # binding.pry
    @fixture_types = FixtureType.includes(:locations).limit(100)
    @fixture_types_data = []
    @fixture_types.each do |ft|
      @fixture_types_data << {DT_RowId: ft.id, name: ft.name, location_count: ft.locations.size, locations: ft.locations}
    end
    render json: {totals: @fixture_types.size, data: @fixture_types_data}.to_json
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = []
  end

  def store_explorer
    # binding.pry
    @locations = Location.limit(rand(7000))
    render json: {totals: @locations.count, data: @locations}.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/fixture_types_helper.rb
module FixtureTypesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/characters/index.html.erb
<h1>Characters</h1>
<table id="character-table" width="100%">
  <thead>
    <tr>
      <th width="15%">Character</th>
      <th width="15%">Movie</th>
      <th width="15">Actor</th>
      <th width="15%">Year</th>
      <th width="40%">About</th>
    </tr>
  </thead>
  <tbody>
    <% @characters.each do |character| %>
      <tr class="<%= cycle("odd", "even") -%>">
        <td><%= character.name %></td>
        <td><%= character.movie %></td>
        <td><%= character.actor %></td>
        <td><%= character.year %></td>
        <td><%= character.about %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- The following css and js files are only needed for fixed header functionality  -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.2/css/fixedHeader.dataTables.min.css">
<script src="https://cdn.datatables.net/fixedheader/3.1.3/js/dataTables.fixedHeader.min.js" type="text/javascript"></script>
<script>
  $(document).ready(function() {
    $("#character-table").dataTable({
      fixedHeader: {
        header: true
      }
    });
  });
</script>

app/views/fixture_types/index.html.erb
<h1 id="totals">--</h1>

<%= form_tag(nested_tables_fixture_types_path, id: 'nested-form', method: :get) do %>
  <%= label_tag(:locations, "Locations") %>
  <%= text_field_tag(:locations) %>
  <%= label_tag(:fixtures, "Fixtures") %>
  <%= text_field_tag(:fixtures) %>
  <%= label_tag(:content, "Content") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("FIND") %>
<% end %>

<table id="nested-table" width="100%">
  <thead>
    <tr>
      <th width="10%"></th>
      <th width="45%">Fixture Type</th>
      <th width="45%">Locations Count</th>
    </tr>
  </thead>
</table>
<script>

$( document ).ready(function() {
  var format = function(row) {
    return '<table id="fixture-type' + row.id() +'" width="100%">' +
      '<thead>' +
        '<tr>' +
          '<th width="20%">Code</th>' +
          '<th width="10">Status</th>' +
          '<th width="10%">Name</th>' +
          '<th width="10%">Region</th>' +
          '<th width="10%">Address</th>' +
          '<th width="10%">City</th>' +
          '<th width="10">State</th>' +
          '<th width="10%">Zip</th>' +
          '<th width="10%">Phone Number</th>' +
        '</tr>' +
      '</thead>' +
    '</table>'

  }

  $('#nested-form').submit(function(e) {
    e.preventDefault();
    var table = $('#nested-table').DataTable({
      destroy: true,
      ajax: "/fixture_types/nested_tables.json",
      columns: [
        {
          "defaultContent": '<i class="fa fa-chevron-right" aria-hidden="true"></i>',
          "className": 'expand'
        },
        { "data": "name" },
        { "data": "location_count" },
      ]
    })
    table.on( 'xhr', function () {
      var json = table.ajax.json();
      $('#totals').text(json.totals)
    });
  })

  $('#nested-table').on('click', 'td.expand', function(){
    // var tr = $('tr')[2]
    $(this).find('i').toggleClass('fa-chevron-right')
    $(this).find('i').toggleClass('fa-chevron-down')
    var table = $('#nested-table').DataTable()
    var tr = $(this).closest('tr');
    var row = table.row( tr );

    if (row.child.isShown()) {
      row.child.hide();
      tr.removeClass('shown');
    }
    else {
      row.child(format(row)).show();
      tr.addClass('shown')
      var subTable = $('#fixture-type' + row.id())
      subTable.DataTable({
      data: row.data().locations,
      columns: [
              { "data": "code" },
              { "data": "status" },
              { "data": "name" },
              { "data": "region" },
              { "data": "address" },
              { "data": "city" },
              { "data": "state" },
              { "data": "zip" },
              { "data": "phone_number" },
            ]
      })
    }
  });

});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataTablesTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<h1 id="totals">--</h1>

<%= form_tag(store_explorer_locations_path, id: 'explorer-form', method: :post) do %>
  <%= label_tag(:locations, "Locations") %>
  <%= text_field_tag(:locations) %>
  <%= label_tag(:fixtures, "Fixtures") %>
  <%= text_field_tag(:fixtures) %>
  <%= label_tag(:content, "Content") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("FIND") %>
<% end %>

<table id="location-table" width="100%">
  <thead>
    <tr>
      <th width="20%">Code</th>
      <th width="10">Status</th>
      <th width="10%">Name</th>
      <th width="10%">Region</th>
      <th width="10%">Address</th>
      <th width="10%">City</th>
      <th width="10">State</th>
      <th width="10%">Zip</th>
      <th width="10%">Phone Number</th>
    </tr>
  </thead>
  <!-- <tbody>
    <% @locations.each do |location| %>
      <tr class="<%= cycle("odd", "even") -%>">
        <td><%= location.code %></td>
        <td><%= location.status %></td>
        <td><%= location.name %></td>
        <td><%= location.region %></td>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= location.state %></td>
        <td><%= location.zip %></td>
        <td><%= location.phone_number %></td>
      </tr>
    <% end %>
  </tbody> -->
</table>